# Generated by Django 5.2.12 on 2026-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='performance',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
